on:
  schedule:
    - cron: "5 16 * * *"
    - cron: "15 21 * * *"

  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  my-job:
    environment: Tweeter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download collection
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow_conclusion: success
          if_no_artifact_found: ignore
          name: collection
          path: ./collection

      - name: Install dependencies
        run: npm install

      - name: Prepare directories
        run: |
          mkdir -p ./collection/
          mkdir -p ./logs/

      - name: Collect
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm run collect -- -U ${{ secrets.TARGET_USERNAME }} -H

      - name: Tweet
        env:
          OPENAI_SECRET: ${{ secrets.OPENAI_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          npm run tweet -- -U ${{ secrets.TARGET_USERNAME }} -W ${{ secrets.WEBHOOK_URL }}

      - name: "Upload Collection"
        uses: actions/upload-artifact@v4
        with:
          name: collection
          path: collection/
          retention-days: 90

      - name: "Upload Logs"
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
          retention-days: 90
